dglab3:
  channel_a:
    avatar_params:
    - /avatar/parameters/TouchAreaA
    - /avatar/parameters/TouchAreaB
    mode: distance
    strength_limit: 100
  channel_b:
    avatar_params:
    - /avatar/parameters/TouchAreaC
    - /avatar/parameters/TouchAreaD
    mode: distance
    strength_limit: 100
version: v0.2
