dglab3:
  channel_a:
    accel_range: 500
    avatar_params:
    - /avatar/parameters/TouchAreaA
    - /avatar/parameters/TouchAreaB
    boost_cooldown: 5
    boost_decay: 20
    boost_threshold: 5
    device_limit: 100
    impact_boost: 0
    impact_boost_max: 20
    impact_boost_min: 0
    impact_enabled: true
    mode: touch
    n_derivative: 1
    recoil_boost: 100
    recoil_enabled: true
    sensitivity: 30
    strength_limit: 100
    threshold: 10
    velocity_range: 50
    wave_freq: 10
  channel_b:
    avatar_params:
    - /avatar/parameters/TouchAreaC
    - /avatar/parameters/TouchAreaD
    device_limit: 100
    impact_boost: 0
    impact_boost_max: 26
    impact_boost_min: 2
    mode: distance
    n_derivative: 0
    recoil_boost: 100
    sensitivity: 100
    strength_limit: 100
    threshold: 10
version: v0.2
